version: '3.9'
services:
  app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      # Ajusta tus variables de entorno
      DATABASE_URL: "postgresql://postgres:secret@db:5432/mydb"
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      